apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}
    app.kubernetes.io/component: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
    app.openshift.io/runtime-version: 1.0.2
  name: {{ .Release.Name }}-cluster
spec:
  ports:
  - name: jgroups
    port: 7800
    protocol: TCP
    targetPort: 7800
  selector:
    app: {{ .Release.Name }}
    deploymentconfig: {{ .Release.Name }}
  clusterIP: None
status: {}
