apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}
    app.kubernetes.io/component: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
    app.openshift.io/runtime-version: 1.0.2
  name: {{ .Release.Name }}
spec:
  ports:
  - name: mqtt
    port: 4321
    protocol: TCP
    targetPort: 4321
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: jolokia
    port: 8778
    protocol: TCP
    targetPort: 8778
  selector:
    app: {{ .Release.Name }}
    deploymentconfig: {{ .Release.Name }}
  sessionAffinity: None
  type: ClusterIP
status: {}
